### ISSUE TITLE
EPIC - SenNet: create and add SenNet ontology to ontology knowledge graphs

### ISSUE THREAD

**Issue by AlanSimmons** [dbmi-pitt/UBKG#17]
We need an "application ontology" for SenNet similar to the ontology that we have for HuBMAP. Like HuBMAP, SenNet will be built using the SimpleKnowledge editor.

Because of similarities between HubMAP and SenNet, it may be possible to use some of the features of the HuBMAP ontology in SenNet. However, HubMAP's ontology was built forensically for a mature project that had a lot of time to grow organically. It is more likely that the SenNet ontology will be built from scratch with a process that is informed by what we learned building the HuBMAP ontology and not necessarily a simple copy and paste.

Task list:

- [ ] Using the SimpleKnowledge framework (spreadsheet and guesdt visualization), build the set of SenNet concepts.
- [ ] Integrate the SenNet file into the generation framework (ontologies.json; skowlnets.py)
- [ ] Refresh the HubMAP/SenNet ontology KG with SenNet data.

**Comment by AlanSimmons** [comment]
[SenNet SimpleKnowledge Spreadsheet](https://docs.google.com/spreadsheets/d/1L5HkcsIw5k5-[A5YqnCGfknZctf3S7oeU1Vu9_hYE3is/edit?usp=sharing)
[SimpleKnowledge Visualization](https://guesdt.com/SimpleKnowledgeVisualization.html?sheet=1L5HkcsIw5k5-A5YqnCGfknZctf3S7oeU1Vu9_hYE3is)

These files are currently stored in the HubMAP Google Drive. The Visualization tool requires permissions to the spreadsheet that are apparently not available in the SenNet folder path.

**Comment by AlanSimmons** [comment]
# Methodology

1. Start from a copy of the HUBMAP ontology’s SimpleKnowledge spreadsheet.
2. Remove artifacts or irrelevant content.
3. Change content to match SenNet.

**Comment by AlanSimmons** [comment]
# What we know now (November 30 2022)

- Information relevant to SenNet is currently stored in [YAML files](https://github.com/sennetconsortium/search-api/tree/main/src/search-schema/data/definitions/enums) in the SenNet implementation of Search API. We’ll convert from this to using the ontology.

- There is some overlap in primary assay types. [This](https://docs.google.com/spreadsheets/d/1LLIbwNWVL1YwTY91Ep73pREn2-r_mZZW/edit?usp=sharing&ouid=117244544244418821461&rtpof=true&sd=true) is the current list of primary assay types.
- There will be some new primary assays for SenNet.
- We should assume that relevant analysis pipelines from HubMAP will be used in SenNet.
- We will need to support Vitessce: with respect to the ontology, this means Vitessce hints.
- We want to include provenance metadata.
- We do not want to manage file information via manifests and file schema documents like we did with HuBMAP; instead, we will want everything encoded in the ontology. There will likely be a domain specific to data set file types.

**Comment by AlanSimmons** [comment]
1. Changed SAB for all codes from HUBMAP to SENNET.

1. Removed nodes and edges related to file URLs.

**Comment by AlanSimmons** [comment]
Aligned to primary assays defined in SenNet [here](https://github.com/sennetconsortium/search-api/blob/main/src/search-schema/data/definitions/enums/assay_types.yaml).

Primary | Action | Reason
---|---|---
Autofluorescence Microscopy | removed| Not in SenNet
Bulk ATAC-seq|removed|Not in SenNet
Cell DIVE (with SPRM and DeepCell pipelines) | removed | Not in SenNet
CODEX | kept | in SenNet
CODEX2 | removed | not in SenNet
DART-FISH | removed | not in SenNet
IMC, IMC2D, IMC3d | removed | not in SenNet
Label-free LC-MS | removed | not in SenNet
Labeled LC-MS | removed | not in SenNet
Untargeted LC-MS | removed | not in SenNet
Lightsheet | removed | not in SenNet
MALDI | removed | not in SenNet
MIBI | kept | in SenNet
NanoDESI | removed | not in SenNet
NanoPOTS | removed | not in SenNet
MXIF| kept | **Question: Does "Multiplexed" in the SenNet assay_types.yaml refer to MXIF?**
PAS Stained Microscopy |kept|**Question: Does this correspond to "Stained Slides"?**
scRNA-Seq|kept|in SenNet
snRNA-Seq|kept|in SenNet
scATAC-Seq, scATAC-seq (SNARE-seq2) Lab Processed,scATAC-seq (SNARE-seq2) SnapATAC, sciATAC-seq [SnapATAC] | removed | not in SenNet
SNARE-Seq, SNARE-Seq2, snATACseq (SNARE-seq2),SNARE-ATACseq2, snRNAseq (SNARE-seq2), SNARE-RNAseq2,snATAC-seq (SNARE-seq2) Lab Processed, snRNA-seq (SNARE-seq2) [Salmon]|removed|not in SenNet
10x-genomics, 10x-genomics-v2, 10x-genomics-v3|removed|not in SenNet
SCI-seq, sciATAC-seq, sciRNAseq, sciRNA-seq [Salmon]|removed|not in SenNet
seqFISH|removed|not in SenNet
snATAC-seq|kept|in SenNet

**Comment by AlanSimmons** [comment]
New concepts *added for* SenNet:

Concept | Comment
---|---
CITE-Seq|cross references a concept in EFO, which we will need to add to the KG.
CosMX - RNA|cross-references a concept in EFO

**Comment by AlanSimmons** [comment]
Changes to Organ domain:
Organ |Action
---|---
Adipose Tissue|added
Aorta|removed
Bladder|removed
Bone Marrow|removed
Fallopian Tube (left, right)|removed
Heart|removed
Bronchus (left, right) | removed
Eye (left, right)|removed
Kidney (left, right)|kept
Knee (left, right) | removed
Large Intestine | kept
Lung (left, right) | kept
Lymph node | kept
Ovary (left, right) | kept
Muscle|added
Pancreas|removed
Placenta|removed
Small Intestine|removed
Skin | kept
Spleen|removed
Thymus|removed
Trachea|removed
Ureter|removed
Uterus|removed

biopsy|removed

**Comment by AlanSimmons** [comment]
Alignment of Sample domain with[ tissue_sample_types.yaml](https://github.com/sennetconsortium/search-api/blob/main/src/search-schema/data/definitions/enums/tissue_sample_types.yaml):

type|action
ataseq|kept
biopsy|kept
blood|added
cell_lysate|kept
codex|kept, but renamed codex_sample to prevent confusion with codex as name of assay
clarity_hydrogel|kept
cryosections_curls_from_fresh_frozen_oct|kept
cryosections_curls_rnalater|kept
ffpe_block|kept
ffpe_slide|kept
fixed_frozen_section_slide|kept
fixed_tissue_piece|kept
flash_frozen_liquid_nitrogen|kept
formalin_fixed_oct_block|kept
fresh_frozen_oct_block|kept
fresh_frozen_section_slide|kept
fresh_frozen_tissue|kept
fresh_frozen_tissue_section|kept
fresh_tissue|kept
frozen_cell_pellet_buffy_coat|kept
gdna|kept
module|kept
nuclei|kept
nuclei_rnalater|kept
organ|kept
organ_piece|kept
other|kept
pbmc|kept
pfa_fixed_frozen_oct_block|kept
plasma|kept
protein|kept
ran_poly_a_enriched|kept (**note:misspelled - should be "rna_poly_a_enriched"**)
rna_total|kept
rnalater_treated_and_stored|kept
rnaseq|kept

**Comment by AlanSimmons** [comment]
# Example Visualizations and Explanations
## Assay type rules

- In general, the dataset for an assay will be described with a different text string. The Data Portal uses the dataset name in searches, not the assay name. (This is more common in HubMAP than SenNet.)
- By default, the node to describe an assay will also correspond to the dataset type. The examples below show both cases–i.e., where the dataset name is the same as the assay name, and where they differ.
- As of December 2, the spreadsheet carries relevant pipelines from HubMAP. A pipeline is relevant for SenNet if it works with one of the primary assay types defined in SenNet.
- The ontology contains hierarchical organizing information that is not defined explicitly in the YAML files. For example, the ontology groups all assays that involve RNA analysis.

## Assay Type: Bulk RNA-Seq
###assay_types.yaml

![Image](https://user-images.githubusercontent.com/10928372/205348750-15c5e661-1d79-4a3b-b367-c10cc1ab2915.png)

### Characteristics

- The dataset name (description) is the same as the assay name. 
- Primary assay
- Contains PII

### Visualization

- Path: SenNet→Assay→Sequencing Assay→RNA Analysis→Bulk RNA-Seq
- Because the assay name and the dataset name are the same, Bulk RNA-Seq is both an assay and a dataset type.
- Notice the polyhierarchies–e.g., RNA Analysis, RNA-seq, Primary. Some of these nodes (e.g., RNA Analysis) group assays by type; others (Primary) by characteristic.
- Notice salmon_rnaseq_bulk. This corresponds to a pipeline (Bulk RNA-seq [Salmon]) carried over from HubMAP.

![Image](https://user-images.githubusercontent.com/10928372/205349034-85fc4c3b-6cb3-40cb-8540-4f56e5d3a352.png)

**Comment by AlanSimmons** [comment]
# Example Visualizations and Explanations - Organs

##Organ: Left Kidney
### organ_types.yaml


![Image](https://user-images.githubusercontent.com/10928372/205349792-4bfb74c4-2c04-4af4-ae05-7f2dfe1bb55e.png)

###Visualization
Path: SenNet→Organ→Kidney(Left)



![Image](https://user-images.githubusercontent.com/10928372/205349896-5da43a5f-6adc-463e-a2cf-53228330b0d7.png)

**Comment by AlanSimmons** [comment]
# Example Visualizations and Explanations - Sample

## Sample metadata
The SenNet sample metadata currently replicates the sample metadata from HuBMAP, which has been optimized for integration with CEDAR.

## Visualization

- Path: SenNet→Sample Metadata
- Example expanded for specimen preparation temperature



![Image](https://user-images.githubusercontent.com/10928372/205350173-60c30acb-7f23-4301-bc95-608f191dff69.png)

**Comment by AlanSimmons** [comment]
# Example Visualizations and Explanations - Sample

## tissue_sample_types.yaml 

- Appears to replicate the same file from HubMAP, with additions for block, section, and suspension.
- Block, section, and suspension are currently also specimen categories from sample metadata.
- The default specimen category is block.


![Image](https://user-images.githubusercontent.com/10928372/205350650-3e923c15-3bcd-45fa-b49f-e07e18535caf.png)

**Comment by AlanSimmons** [comment]
# Visualization: Data Access Level

Path: SenNet -> Access Control -> Data Access Level



![Image](https://user-images.githubusercontent.com/10928372/205353243-493b3698-2978-4bf2-bc60-9316ea0f590d.png)

**Comment by AlanSimmons** [comment]
# Visualization: Entity

- The existing **Dataset_Type** node was renamed **Dataset**.
- **Dataset** and **Sample** existed previously.


![Image](https://user-images.githubusercontent.com/10928372/205362952-0223b34e-9b1a-4781-ab4d-19fa08ab40f8.png)

**Comment by AlanSimmons** [comment]
The initial version of the SenNET application ontology was integrated into the UBKG framework.
